### ISSUE TITLE
File Extensions to Clean

### ISSUE THREAD

**Issue by SamuelCabralCruz** [James-Yu/Atom-LaTeX#107]
I am trying to automatically clean the .nlo, .nlg, .nls file extensions produced by the [nomenclature package](http://cs.brown.edu/about/system/managed/latex/doc/nomencl.pdf) using the **Ctrl + Alt + C** keyboard shortcut. The problem is that that the following configuration seems to be ignored by the atom-latex package.
```yaml
  "atom-latex":
    build_after_save: false
    file_ext_to_clean: "*.aux, *.bbl, *.blg, *.idx, *.ind, *.lof, *.lot, *.out, *.toc, *.acn, *.acr, *.alg, *.glg, *.glo, *.gls, *.nlg, *.nlo, *.nls, *.ist, *.fls, *.log, *.fdb_latexmk"
    latexmk_param: "-synctex=1 -interaction=nonstopmode -file-line-error -pdf --shell-escape"
    preview_after_build: "View in PDF viewer tab"
    save_on_build: true
```
Thanks in advance!
