### ISSUE TITLE
ENH: Improved suggestions for environments

### ISSUE THREAD

**Issue by mcocdawc** [James-Yu/Atom-LaTeX#137]
(Disclaimer: I don't know coffescript.)

Currently the additionalInserts for environments are specified like this:
```
    latex:
      figure:
        text: 'figure'
        additionalInsert: '\\caption{title}'
```
It would be great to have similar behaviour as the self defined snippets by atom. 
This means that it is possible to specify a point where the cursor jumps to upon pressing tab.
Something along the line of:
```
    latex:
      figure:
        text: 'figure'
        additionalInsert: '\\caption{${1:title}}'
```
Unfortunately this does not work and I don't know enough coffescript to implement it myself.
